FROM golang:1.24-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/hackaton-service ./cmd/hackaton-service

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates

COPY --from=builder /app/hackaton-service .

RUN adduser -D -u 1000 appuser
USER appuser

EXPOSE 50052

CMD ["./hackaton-service"]

