// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type HackathonAnnouncement struct {
	ID              uuid.UUID          `json:"id"`
	HackathonID     uuid.UUID          `json:"hackathon_id"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type HackathonHackathon struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	ShortDescription     string             `json:"short_description"`
	Description          string             `json:"description"`
	LocationOnline       bool               `json:"location_online"`
	LocationCity         string             `json:"location_city"`
	LocationCountry      string             `json:"location_country"`
	LocationVenue        string             `json:"location_venue"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	RegistrationOpensAt  pgtype.Timestamptz `json:"registration_opens_at"`
	RegistrationClosesAt pgtype.Timestamptz `json:"registration_closes_at"`
	SubmissionsOpensAt   pgtype.Timestamptz `json:"submissions_opens_at"`
	SubmissionsClosesAt  pgtype.Timestamptz `json:"submissions_closes_at"`
	JudgingEndsAt        pgtype.Timestamptz `json:"judging_ends_at"`
	Stage                string             `json:"stage"`
	State                string             `json:"state"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	ResultPublishedAt    pgtype.Timestamptz `json:"result_published_at"`
	Task                 string             `json:"task"`
	Result               string             `json:"result"`
	TeamSizeMax          int32              `json:"team_size_max"`
	AllowIndividual      bool               `json:"allow_individual"`
	AllowTeam            bool               `json:"allow_team"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type HackathonHackathonLink struct {
	ID          uuid.UUID `json:"id"`
	HackathonID uuid.UUID `json:"hackathon_id"`
	Title       string    `json:"title"`
	Url         string    `json:"url"`
}

type HackathonIdempotencyKey struct {
	Key          string    `json:"key"`
	Scope        string    `json:"scope"`
	RequestHash  string    `json:"request_hash"`
	ResponseBlob []byte    `json:"response_blob"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type HackathonOutboxEvent struct {
	ID            uuid.UUID `json:"id"`
	AggregateID   string    `json:"aggregate_id"`
	AggregateType string    `json:"aggregate_type"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	Status        string    `json:"status"`
	AttemptCount  int32     `json:"attempt_count"`
	LastError     string    `json:"last_error"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
