// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type TeamIdempotencyKey struct {
	Key          string    `json:"key"`
	Scope        string    `json:"scope"`
	RequestHash  string    `json:"request_hash"`
	ResponseBlob []byte    `json:"response_blob"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type TeamJoinRequest struct {
	ID              uuid.UUID          `json:"id"`
	HackathonID     uuid.UUID          `json:"hackathon_id"`
	TeamID          uuid.UUID          `json:"team_id"`
	VacancyID       uuid.UUID          `json:"vacancy_id"`
	RequesterUserID uuid.UUID          `json:"requester_user_id"`
	Message         string             `json:"message"`
	Status          string             `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type TeamMembership struct {
	TeamID            uuid.UUID   `json:"team_id"`
	UserID            uuid.UUID   `json:"user_id"`
	IsCaptain         bool        `json:"is_captain"`
	AssignedVacancyID pgtype.UUID `json:"assigned_vacancy_id"`
	JoinedAt          time.Time   `json:"joined_at"`
}

type TeamOutboxEvent struct {
	ID            uuid.UUID `json:"id"`
	AggregateID   string    `json:"aggregate_id"`
	AggregateType string    `json:"aggregate_type"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	Status        string    `json:"status"`
	AttemptCount  int32     `json:"attempt_count"`
	LastError     string    `json:"last_error"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type TeamTeam struct {
	ID          uuid.UUID `json:"id"`
	HackathonID uuid.UUID `json:"hackathon_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsJoinable  bool      `json:"is_joinable"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type TeamTeamInvitation struct {
	ID              uuid.UUID          `json:"id"`
	HackathonID     uuid.UUID          `json:"hackathon_id"`
	TeamID          uuid.UUID          `json:"team_id"`
	VacancyID       uuid.UUID          `json:"vacancy_id"`
	TargetUserID    uuid.UUID          `json:"target_user_id"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	Message         string             `json:"message"`
	Status          string             `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type TeamVacancy struct {
	ID              uuid.UUID   `json:"id"`
	TeamID          uuid.UUID   `json:"team_id"`
	Description     string      `json:"description"`
	DesiredRoleIds  []uuid.UUID `json:"desired_role_ids"`
	DesiredSkillIds []uuid.UUID `json:"desired_skill_ids"`
	SlotsTotal      int64       `json:"slots_total"`
	SlotsOpen       int64       `json:"slots_open"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	IsSystem        bool        `json:"is_system"`
}
