// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SubmissionIdempotencyKey struct {
	Key          string    `json:"key"`
	Scope        string    `json:"scope"`
	RequestHash  string    `json:"request_hash"`
	ResponseBlob []byte    `json:"response_blob"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type SubmissionSubmission struct {
	ID              uuid.UUID `json:"id"`
	HackathonID     uuid.UUID `json:"hackathon_id"`
	OwnerKind       string    `json:"owner_kind"`
	OwnerID         uuid.UUID `json:"owner_id"`
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	IsFinal         bool      `json:"is_final"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type SubmissionSubmissionFile struct {
	ID           uuid.UUID          `json:"id"`
	SubmissionID uuid.UUID          `json:"submission_id"`
	Filename     string             `json:"filename"`
	SizeBytes    int64              `json:"size_bytes"`
	ContentType  string             `json:"content_type"`
	StorageKey   string             `json:"storage_key"`
	UploadStatus string             `json:"upload_status"`
	CreatedAt    time.Time          `json:"created_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}
