// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity/v1/services/auth_service.proto

package services

import (
	v1 "github.com/belikoooova/hackaton-platform-api/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Login:
	//
	//	*RegisterRequest_Email
	Login          isRegisterRequest_Login `protobuf_oneof:"login"`
	Password       string                  `protobuf:"bytes,10,opt,name=password,proto3" json:"password,omitempty"`
	FirstName      string                  `protobuf:"bytes,20,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                  `protobuf:"bytes,21,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username       string                  `protobuf:"bytes,22,opt,name=username,proto3" json:"username,omitempty"`
	Timezone       string                  `protobuf:"bytes,23,opt,name=timezone,proto3" json:"timezone,omitempty"`
	IdempotencyKey *v1.IdempotencyKey      `protobuf:"bytes,30,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_identity_v1_services_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() isRegisterRequest_Login {
	if x != nil {
		return x.Login
	}
	return nil
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Login.(*RegisterRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *RegisterRequest) GetIdempotencyKey() *v1.IdempotencyKey {
	if x != nil {
		return x.IdempotencyKey
	}
	return nil
}

type isRegisterRequest_Login interface {
	isRegisterRequest_Login()
}

type RegisterRequest_Email struct {
	Email string `protobuf:"bytes,1,opt,name=email,proto3,oneof"`
}

func (*RegisterRequest_Email) isRegisterRequest_Login() {}

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Login:
	//
	//	*LoginRequest_Email
	//	*LoginRequest_Username
	Login         isLoginRequest_Login `protobuf_oneof:"login"`
	Password      string               `protobuf:"bytes,10,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_identity_v1_services_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetLogin() isLoginRequest_Login {
	if x != nil {
		return x.Login
	}
	return nil
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Login.(*LoginRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Login.(*LoginRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type isLoginRequest_Login interface {
	isLoginRequest_Login()
}

type LoginRequest_Email struct {
	Email string `protobuf:"bytes,1,opt,name=email,proto3,oneof"`
}

type LoginRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

func (*LoginRequest_Email) isLoginRequest_Login() {}

func (*LoginRequest_Username) isLoginRequest_Login() {}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_identity_v1_services_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_identity_v1_services_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type AuthResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=access_expires_at,json=accessExpiresAt,proto3" json:"access_expires_at,omitempty"`
	RefreshExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=refresh_expires_at,json=refreshExpiresAt,proto3" json:"refresh_expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_identity_v1_services_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *AuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthResponse) GetAccessExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessExpiresAt
	}
	return nil
}

func (x *AuthResponse) GetRefreshExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshExpiresAt
	}
	return nil
}

var File_identity_v1_services_auth_service_proto protoreflect.FileDescriptor

const file_identity_v1_services_auth_service_proto_rawDesc = "" +
	"\n" +
	"'identity/v1/services/auth_service.proto\x12\x14identity.v1.services\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bcommon/v1/idempotency.proto\"\x86\x02\n" +
	"\x0fRegisterRequest\x12\x16\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x12\x1a\n" +
	"\bpassword\x18\n" +
	" \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x14 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x15 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x16 \x01(\tR\busername\x12\x1a\n" +
	"\btimezone\x18\x17 \x01(\tR\btimezone\x12B\n" +
	"\x0fidempotency_key\x18\x1e \x01(\v2\x19.common.v1.IdempotencyKeyR\x0eidempotencyKeyB\a\n" +
	"\x05login\"i\n" +
	"\fLoginRequest\x12\x16\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x12\x1a\n" +
	"\bpassword\x18\n" +
	" \x01(\tR\bpasswordB\a\n" +
	"\x05login\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xe8\x01\n" +
	"\fAuthResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12F\n" +
	"\x11access_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0faccessExpiresAt\x12H\n" +
	"\x12refresh_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x10refreshExpiresAt2\xc3\x03\n" +
	"\vAuthService\x12s\n" +
	"\bRegister\x12%.identity.v1.services.RegisterRequest\x1a\".identity.v1.services.AuthResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/register\x12j\n" +
	"\x05Login\x12\".identity.v1.services.LoginRequest\x1a\".identity.v1.services.AuthResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12p\n" +
	"\aRefresh\x12$.identity.v1.services.RefreshRequest\x1a\".identity.v1.services.AuthResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/auth/refresh\x12a\n" +
	"\x06Logout\x12#.identity.v1.services.LogoutRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logoutBPZNgithub.com/belikoooova/hackaton-platform-api/api/identity/v1/services;servicesb\x06proto3"

var (
	file_identity_v1_services_auth_service_proto_rawDescOnce sync.Once
	file_identity_v1_services_auth_service_proto_rawDescData []byte
)

func file_identity_v1_services_auth_service_proto_rawDescGZIP() []byte {
	file_identity_v1_services_auth_service_proto_rawDescOnce.Do(func() {
		file_identity_v1_services_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_services_auth_service_proto_rawDesc), len(file_identity_v1_services_auth_service_proto_rawDesc)))
	})
	return file_identity_v1_services_auth_service_proto_rawDescData
}

var file_identity_v1_services_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_identity_v1_services_auth_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: identity.v1.services.RegisterRequest
	(*LoginRequest)(nil),          // 1: identity.v1.services.LoginRequest
	(*RefreshRequest)(nil),        // 2: identity.v1.services.RefreshRequest
	(*LogoutRequest)(nil),         // 3: identity.v1.services.LogoutRequest
	(*AuthResponse)(nil),          // 4: identity.v1.services.AuthResponse
	(*v1.IdempotencyKey)(nil),     // 5: common.v1.IdempotencyKey
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_identity_v1_services_auth_service_proto_depIdxs = []int32{
	5, // 0: identity.v1.services.RegisterRequest.idempotency_key:type_name -> common.v1.IdempotencyKey
	6, // 1: identity.v1.services.AuthResponse.access_expires_at:type_name -> google.protobuf.Timestamp
	6, // 2: identity.v1.services.AuthResponse.refresh_expires_at:type_name -> google.protobuf.Timestamp
	0, // 3: identity.v1.services.AuthService.Register:input_type -> identity.v1.services.RegisterRequest
	1, // 4: identity.v1.services.AuthService.Login:input_type -> identity.v1.services.LoginRequest
	2, // 5: identity.v1.services.AuthService.Refresh:input_type -> identity.v1.services.RefreshRequest
	3, // 6: identity.v1.services.AuthService.Logout:input_type -> identity.v1.services.LogoutRequest
	4, // 7: identity.v1.services.AuthService.Register:output_type -> identity.v1.services.AuthResponse
	4, // 8: identity.v1.services.AuthService.Login:output_type -> identity.v1.services.AuthResponse
	4, // 9: identity.v1.services.AuthService.Refresh:output_type -> identity.v1.services.AuthResponse
	7, // 10: identity.v1.services.AuthService.Logout:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_identity_v1_services_auth_service_proto_init() }
func file_identity_v1_services_auth_service_proto_init() {
	if File_identity_v1_services_auth_service_proto != nil {
		return
	}
	file_identity_v1_services_auth_service_proto_msgTypes[0].OneofWrappers = []any{
		(*RegisterRequest_Email)(nil),
	}
	file_identity_v1_services_auth_service_proto_msgTypes[1].OneofWrappers = []any{
		(*LoginRequest_Email)(nil),
		(*LoginRequest_Username)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_services_auth_service_proto_rawDesc), len(file_identity_v1_services_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_v1_services_auth_service_proto_goTypes,
		DependencyIndexes: file_identity_v1_services_auth_service_proto_depIdxs,
		MessageInfos:      file_identity_v1_services_auth_service_proto_msgTypes,
	}.Build()
	File_identity_v1_services_auth_service_proto = out.File
	file_identity_v1_services_auth_service_proto_goTypes = nil
	file_identity_v1_services_auth_service_proto_depIdxs = nil
}
