// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity/v1/services/me_service.proto

package services

import (
	v1 "github.com/belikoooova/hackaton-platform-api/api/common/v1"
	v11 "github.com/belikoooova/hackaton-platform-api/api/identity/v1"
	entities "github.com/belikoooova/hackaton-platform-api/api/identity/v1/entities"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_identity_v1_services_me_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_me_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_me_service_proto_rawDescGZIP(), []int{0}
}

type GetMeResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	User   *entities.User         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Skills []*entities.Skill      `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	// My contacts include per-contact visibility.
	Contacts []*entities.MyContact `protobuf:"bytes,3,rep,name=contacts,proto3" json:"contacts,omitempty"`
	// Global visibility (skills + contacts).
	Visibility    *entities.VisibilitySettings `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_identity_v1_services_me_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_me_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_me_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetMeResponse) GetUser() *entities.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetMeResponse) GetSkills() []*entities.Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *GetMeResponse) GetContacts() []*entities.MyContact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *GetMeResponse) GetVisibility() *entities.VisibilitySettings {
	if x != nil {
		return x.Visibility
	}
	return nil
}

type UpdateMeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FirstName      string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	AvatarUrl      string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Timezone       string                 `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	IdempotencyKey *v1.IdempotencyKey     `protobuf:"bytes,10,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMeRequest) Reset() {
	*x = UpdateMeRequest{}
	mi := &file_identity_v1_services_me_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeRequest) ProtoMessage() {}

func (x *UpdateMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_me_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeRequest.ProtoReflect.Descriptor instead.
func (*UpdateMeRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_me_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMeRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateMeRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateMeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateMeRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdateMeRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UpdateMeRequest) GetIdempotencyKey() *v1.IdempotencyKey {
	if x != nil {
		return x.IdempotencyKey
	}
	return nil
}

type UpdateMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *entities.User         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeResponse) Reset() {
	*x = UpdateMeResponse{}
	mi := &file_identity_v1_services_me_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeResponse) ProtoMessage() {}

func (x *UpdateMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_me_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeResponse.ProtoReflect.Descriptor instead.
func (*UpdateMeResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_me_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMeResponse) GetUser() *entities.User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateMySkillsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Replace-all semantics:
	CatalogSkillIds  []string            `protobuf:"bytes,1,rep,name=catalog_skill_ids,json=catalogSkillIds,proto3" json:"catalog_skill_ids,omitempty"`
	UserSkills       []string            `protobuf:"bytes,2,rep,name=user_skills,json=userSkills,proto3" json:"user_skills,omitempty"`
	SkillsVisibility v11.VisibilityLevel `protobuf:"varint,3,opt,name=skills_visibility,json=skillsVisibility,proto3,enum=identity.v1.VisibilityLevel" json:"skills_visibility,omitempty"`
	IdempotencyKey   *v1.IdempotencyKey  `protobuf:"bytes,10,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateMySkillsRequest) Reset() {
	*x = UpdateMySkillsRequest{}
	mi := &file_identity_v1_services_me_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMySkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMySkillsRequest) ProtoMessage() {}

func (x *UpdateMySkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_me_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMySkillsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMySkillsRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_me_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMySkillsRequest) GetCatalogSkillIds() []string {
	if x != nil {
		return x.CatalogSkillIds
	}
	return nil
}

func (x *UpdateMySkillsRequest) GetUserSkills() []string {
	if x != nil {
		return x.UserSkills
	}
	return nil
}

func (x *UpdateMySkillsRequest) GetSkillsVisibility() v11.VisibilityLevel {
	if x != nil {
		return x.SkillsVisibility
	}
	return v11.VisibilityLevel(0)
}

func (x *UpdateMySkillsRequest) GetIdempotencyKey() *v1.IdempotencyKey {
	if x != nil {
		return x.IdempotencyKey
	}
	return nil
}

type UpdateMySkillsResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Skills        []*entities.Skill            `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	Visibility    *entities.VisibilitySettings `protobuf:"bytes,2,opt,name=visibility,proto3" json:"visibility,omitempty"` // return updated global visibility
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMySkillsResponse) Reset() {
	*x = UpdateMySkillsResponse{}
	mi := &file_identity_v1_services_me_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMySkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMySkillsResponse) ProtoMessage() {}

func (x *UpdateMySkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_me_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMySkillsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMySkillsResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_me_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMySkillsResponse) GetSkills() []*entities.Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *UpdateMySkillsResponse) GetVisibility() *entities.VisibilitySettings {
	if x != nil {
		return x.Visibility
	}
	return nil
}

type UpdateMyContactsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Replace-all semantics:
	Contacts           []*entities.MyContact `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	ContactsVisibility v11.VisibilityLevel   `protobuf:"varint,2,opt,name=contacts_visibility,json=contactsVisibility,proto3,enum=identity.v1.VisibilityLevel" json:"contacts_visibility,omitempty"`
	IdempotencyKey     *v1.IdempotencyKey    `protobuf:"bytes,10,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateMyContactsRequest) Reset() {
	*x = UpdateMyContactsRequest{}
	mi := &file_identity_v1_services_me_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMyContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMyContactsRequest) ProtoMessage() {}

func (x *UpdateMyContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_me_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMyContactsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMyContactsRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_me_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMyContactsRequest) GetContacts() []*entities.MyContact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *UpdateMyContactsRequest) GetContactsVisibility() v11.VisibilityLevel {
	if x != nil {
		return x.ContactsVisibility
	}
	return v11.VisibilityLevel(0)
}

func (x *UpdateMyContactsRequest) GetIdempotencyKey() *v1.IdempotencyKey {
	if x != nil {
		return x.IdempotencyKey
	}
	return nil
}

type UpdateMyContactsResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Contacts      []*entities.MyContact        `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	Visibility    *entities.VisibilitySettings `protobuf:"bytes,2,opt,name=visibility,proto3" json:"visibility,omitempty"` // return updated global visibility
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMyContactsResponse) Reset() {
	*x = UpdateMyContactsResponse{}
	mi := &file_identity_v1_services_me_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMyContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMyContactsResponse) ProtoMessage() {}

func (x *UpdateMyContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_me_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMyContactsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMyContactsResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_me_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMyContactsResponse) GetContacts() []*entities.MyContact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *UpdateMyContactsResponse) GetVisibility() *entities.VisibilitySettings {
	if x != nil {
		return x.Visibility
	}
	return nil
}

var File_identity_v1_services_me_service_proto protoreflect.FileDescriptor

const file_identity_v1_services_me_service_proto_rawDesc = "" +
	"\n" +
	"%identity/v1/services/me_service.proto\x12\x14identity.v1.services\x1a\x1cgoogle/api/annotations.proto\x1a\x18identity/v1/common.proto\x1a\x1fidentity/v1/entities/user.proto\x1a identity/v1/entities/skill.proto\x1a\"identity/v1/entities/contact.proto\x1a%identity/v1/entities/visibility.proto\x1a\x1bcommon/v1/idempotency.proto\"\x0e\n" +
	"\fGetMeRequest\"\xfb\x01\n" +
	"\rGetMeResponse\x12.\n" +
	"\x04user\x18\x01 \x01(\v2\x1a.identity.v1.entities.UserR\x04user\x123\n" +
	"\x06skills\x18\x02 \x03(\v2\x1b.identity.v1.entities.SkillR\x06skills\x12;\n" +
	"\bcontacts\x18\x03 \x03(\v2\x1f.identity.v1.entities.MyContactR\bcontacts\x12H\n" +
	"\n" +
	"visibility\x18\x04 \x01(\v2(.identity.v1.entities.VisibilitySettingsR\n" +
	"visibility\"\xe8\x01\n" +
	"\x0fUpdateMeRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\x12B\n" +
	"\x0fidempotency_key\x18\n" +
	" \x01(\v2\x19.common.v1.IdempotencyKeyR\x0eidempotencyKey\"B\n" +
	"\x10UpdateMeResponse\x12.\n" +
	"\x04user\x18\x01 \x01(\v2\x1a.identity.v1.entities.UserR\x04user\"\xf3\x01\n" +
	"\x15UpdateMySkillsRequest\x12*\n" +
	"\x11catalog_skill_ids\x18\x01 \x03(\tR\x0fcatalogSkillIds\x12\x1f\n" +
	"\vuser_skills\x18\x02 \x03(\tR\n" +
	"userSkills\x12I\n" +
	"\x11skills_visibility\x18\x03 \x01(\x0e2\x1c.identity.v1.VisibilityLevelR\x10skillsVisibility\x12B\n" +
	"\x0fidempotency_key\x18\n" +
	" \x01(\v2\x19.common.v1.IdempotencyKeyR\x0eidempotencyKey\"\x97\x01\n" +
	"\x16UpdateMySkillsResponse\x123\n" +
	"\x06skills\x18\x01 \x03(\v2\x1b.identity.v1.entities.SkillR\x06skills\x12H\n" +
	"\n" +
	"visibility\x18\x02 \x01(\v2(.identity.v1.entities.VisibilitySettingsR\n" +
	"visibility\"\xe9\x01\n" +
	"\x17UpdateMyContactsRequest\x12;\n" +
	"\bcontacts\x18\x01 \x03(\v2\x1f.identity.v1.entities.MyContactR\bcontacts\x12M\n" +
	"\x13contacts_visibility\x18\x02 \x01(\x0e2\x1c.identity.v1.VisibilityLevelR\x12contactsVisibility\x12B\n" +
	"\x0fidempotency_key\x18\n" +
	" \x01(\v2\x19.common.v1.IdempotencyKeyR\x0eidempotencyKey\"\xa1\x01\n" +
	"\x18UpdateMyContactsResponse\x12;\n" +
	"\bcontacts\x18\x01 \x03(\v2\x1f.identity.v1.entities.MyContactR\bcontacts\x12H\n" +
	"\n" +
	"visibility\x18\x02 \x01(\v2(.identity.v1.entities.VisibilitySettingsR\n" +
	"visibility2\x8b\x04\n" +
	"\tMeService\x12f\n" +
	"\x05GetMe\x12\".identity.v1.services.GetMeRequest\x1a#.identity.v1.services.GetMeResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/users/me\x12r\n" +
	"\bUpdateMe\x12%.identity.v1.services.UpdateMeRequest\x1a&.identity.v1.services.UpdateMeResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\x1a\f/v1/users/me\x12\x8b\x01\n" +
	"\x0eUpdateMySkills\x12+.identity.v1.services.UpdateMySkillsRequest\x1a,.identity.v1.services.UpdateMySkillsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v1/users/me/skills\x12\x93\x01\n" +
	"\x10UpdateMyContacts\x12-.identity.v1.services.UpdateMyContactsRequest\x1a..identity.v1.services.UpdateMyContactsResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/v1/users/me/contactsBPZNgithub.com/belikoooova/hackaton-platform-api/api/identity/v1/services;servicesb\x06proto3"

var (
	file_identity_v1_services_me_service_proto_rawDescOnce sync.Once
	file_identity_v1_services_me_service_proto_rawDescData []byte
)

func file_identity_v1_services_me_service_proto_rawDescGZIP() []byte {
	file_identity_v1_services_me_service_proto_rawDescOnce.Do(func() {
		file_identity_v1_services_me_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_services_me_service_proto_rawDesc), len(file_identity_v1_services_me_service_proto_rawDesc)))
	})
	return file_identity_v1_services_me_service_proto_rawDescData
}

var file_identity_v1_services_me_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_identity_v1_services_me_service_proto_goTypes = []any{
	(*GetMeRequest)(nil),                // 0: identity.v1.services.GetMeRequest
	(*GetMeResponse)(nil),               // 1: identity.v1.services.GetMeResponse
	(*UpdateMeRequest)(nil),             // 2: identity.v1.services.UpdateMeRequest
	(*UpdateMeResponse)(nil),            // 3: identity.v1.services.UpdateMeResponse
	(*UpdateMySkillsRequest)(nil),       // 4: identity.v1.services.UpdateMySkillsRequest
	(*UpdateMySkillsResponse)(nil),      // 5: identity.v1.services.UpdateMySkillsResponse
	(*UpdateMyContactsRequest)(nil),     // 6: identity.v1.services.UpdateMyContactsRequest
	(*UpdateMyContactsResponse)(nil),    // 7: identity.v1.services.UpdateMyContactsResponse
	(*entities.User)(nil),               // 8: identity.v1.entities.User
	(*entities.Skill)(nil),              // 9: identity.v1.entities.Skill
	(*entities.MyContact)(nil),          // 10: identity.v1.entities.MyContact
	(*entities.VisibilitySettings)(nil), // 11: identity.v1.entities.VisibilitySettings
	(*v1.IdempotencyKey)(nil),           // 12: common.v1.IdempotencyKey
	(v11.VisibilityLevel)(0),            // 13: identity.v1.VisibilityLevel
}
var file_identity_v1_services_me_service_proto_depIdxs = []int32{
	8,  // 0: identity.v1.services.GetMeResponse.user:type_name -> identity.v1.entities.User
	9,  // 1: identity.v1.services.GetMeResponse.skills:type_name -> identity.v1.entities.Skill
	10, // 2: identity.v1.services.GetMeResponse.contacts:type_name -> identity.v1.entities.MyContact
	11, // 3: identity.v1.services.GetMeResponse.visibility:type_name -> identity.v1.entities.VisibilitySettings
	12, // 4: identity.v1.services.UpdateMeRequest.idempotency_key:type_name -> common.v1.IdempotencyKey
	8,  // 5: identity.v1.services.UpdateMeResponse.user:type_name -> identity.v1.entities.User
	13, // 6: identity.v1.services.UpdateMySkillsRequest.skills_visibility:type_name -> identity.v1.VisibilityLevel
	12, // 7: identity.v1.services.UpdateMySkillsRequest.idempotency_key:type_name -> common.v1.IdempotencyKey
	9,  // 8: identity.v1.services.UpdateMySkillsResponse.skills:type_name -> identity.v1.entities.Skill
	11, // 9: identity.v1.services.UpdateMySkillsResponse.visibility:type_name -> identity.v1.entities.VisibilitySettings
	10, // 10: identity.v1.services.UpdateMyContactsRequest.contacts:type_name -> identity.v1.entities.MyContact
	13, // 11: identity.v1.services.UpdateMyContactsRequest.contacts_visibility:type_name -> identity.v1.VisibilityLevel
	12, // 12: identity.v1.services.UpdateMyContactsRequest.idempotency_key:type_name -> common.v1.IdempotencyKey
	10, // 13: identity.v1.services.UpdateMyContactsResponse.contacts:type_name -> identity.v1.entities.MyContact
	11, // 14: identity.v1.services.UpdateMyContactsResponse.visibility:type_name -> identity.v1.entities.VisibilitySettings
	0,  // 15: identity.v1.services.MeService.GetMe:input_type -> identity.v1.services.GetMeRequest
	2,  // 16: identity.v1.services.MeService.UpdateMe:input_type -> identity.v1.services.UpdateMeRequest
	4,  // 17: identity.v1.services.MeService.UpdateMySkills:input_type -> identity.v1.services.UpdateMySkillsRequest
	6,  // 18: identity.v1.services.MeService.UpdateMyContacts:input_type -> identity.v1.services.UpdateMyContactsRequest
	1,  // 19: identity.v1.services.MeService.GetMe:output_type -> identity.v1.services.GetMeResponse
	3,  // 20: identity.v1.services.MeService.UpdateMe:output_type -> identity.v1.services.UpdateMeResponse
	5,  // 21: identity.v1.services.MeService.UpdateMySkills:output_type -> identity.v1.services.UpdateMySkillsResponse
	7,  // 22: identity.v1.services.MeService.UpdateMyContacts:output_type -> identity.v1.services.UpdateMyContactsResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_identity_v1_services_me_service_proto_init() }
func file_identity_v1_services_me_service_proto_init() {
	if File_identity_v1_services_me_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_services_me_service_proto_rawDesc), len(file_identity_v1_services_me_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_v1_services_me_service_proto_goTypes,
		DependencyIndexes: file_identity_v1_services_me_service_proto_depIdxs,
		MessageInfos:      file_identity_v1_services_me_service_proto_msgTypes,
	}.Build()
	File_identity_v1_services_me_service_proto = out.File
	file_identity_v1_services_me_service_proto_goTypes = nil
	file_identity_v1_services_me_service_proto_depIdxs = nil
}
