// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity/v1/services/ping_service.proto

package services

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_identity_v1_services_ping_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_ping_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_ping_service_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_identity_v1_services_ping_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_ping_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_ping_service_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_identity_v1_services_ping_service_proto protoreflect.FileDescriptor

const file_identity_v1_services_ping_service_proto_rawDesc = "" +
	"\n" +
	"'identity/v1/services/ping_service.proto\x12\x14identity.v1.services\x1a\x1cgoogle/api/annotations.proto\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2{\n" +
	"\vPingService\x12l\n" +
	"\x04Ping\x12!.identity.v1.services.PingRequest\x1a\".identity.v1.services.PingResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/identity/pingBPZNgithub.com/belikoooova/hackaton-platform-api/api/identity/v1/services;servicesb\x06proto3"

var (
	file_identity_v1_services_ping_service_proto_rawDescOnce sync.Once
	file_identity_v1_services_ping_service_proto_rawDescData []byte
)

func file_identity_v1_services_ping_service_proto_rawDescGZIP() []byte {
	file_identity_v1_services_ping_service_proto_rawDescOnce.Do(func() {
		file_identity_v1_services_ping_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_services_ping_service_proto_rawDesc), len(file_identity_v1_services_ping_service_proto_rawDesc)))
	})
	return file_identity_v1_services_ping_service_proto_rawDescData
}

var file_identity_v1_services_ping_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_identity_v1_services_ping_service_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: identity.v1.services.PingRequest
	(*PingResponse)(nil), // 1: identity.v1.services.PingResponse
}
var file_identity_v1_services_ping_service_proto_depIdxs = []int32{
	0, // 0: identity.v1.services.PingService.Ping:input_type -> identity.v1.services.PingRequest
	1, // 1: identity.v1.services.PingService.Ping:output_type -> identity.v1.services.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_identity_v1_services_ping_service_proto_init() }
func file_identity_v1_services_ping_service_proto_init() {
	if File_identity_v1_services_ping_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_services_ping_service_proto_rawDesc), len(file_identity_v1_services_ping_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_v1_services_ping_service_proto_goTypes,
		DependencyIndexes: file_identity_v1_services_ping_service_proto_depIdxs,
		MessageInfos:      file_identity_v1_services_ping_service_proto_msgTypes,
	}.Build()
	File_identity_v1_services_ping_service_proto = out.File
	file_identity_v1_services_ping_service_proto_goTypes = nil
	file_identity_v1_services_ping_service_proto_depIdxs = nil
}
