// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity/v1/services/skills_service.proto

package services

import (
	v1 "github.com/belikoooova/hackaton-platform-api/api/common/v1"
	entities "github.com/belikoooova/hackaton-platform-api/api/identity/v1/entities"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSkillCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *v1.Query              `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillCatalogRequest) Reset() {
	*x = ListSkillCatalogRequest{}
	mi := &file_identity_v1_services_skills_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillCatalogRequest) ProtoMessage() {}

func (x *ListSkillCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_skills_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillCatalogRequest.ProtoReflect.Descriptor instead.
func (*ListSkillCatalogRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_skills_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListSkillCatalogRequest) GetQuery() *v1.Query {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListSkillCatalogResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Skills        []*entities.CatalogSkill `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	Page          *v1.PageResponse         `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillCatalogResponse) Reset() {
	*x = ListSkillCatalogResponse{}
	mi := &file_identity_v1_services_skills_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillCatalogResponse) ProtoMessage() {}

func (x *ListSkillCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_skills_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillCatalogResponse.ProtoReflect.Descriptor instead.
func (*ListSkillCatalogResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_skills_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListSkillCatalogResponse) GetSkills() []*entities.CatalogSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ListSkillCatalogResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_identity_v1_services_skills_service_proto protoreflect.FileDescriptor

const file_identity_v1_services_skills_service_proto_rawDesc = "" +
	"\n" +
	")identity/v1/services/skills_service.proto\x12\x14identity.v1.services\x1a\x1cgoogle/api/annotations.proto\x1a\x15common/v1/query.proto\x1a identity/v1/entities/skill.proto\"A\n" +
	"\x17ListSkillCatalogRequest\x12&\n" +
	"\x05query\x18\x01 \x01(\v2\x10.common.v1.QueryR\x05query\"\x83\x01\n" +
	"\x18ListSkillCatalogResponse\x12:\n" +
	"\x06skills\x18\x01 \x03(\v2\".identity.v1.entities.CatalogSkillR\x06skills\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.common.v1.PageResponseR\x04page2\x9f\x01\n" +
	"\rSkillsService\x12\x8d\x01\n" +
	"\x10ListSkillCatalog\x12-.identity.v1.services.ListSkillCatalogRequest\x1a..identity.v1.services.ListSkillCatalogResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/skills:listBPZNgithub.com/belikoooova/hackaton-platform-api/api/identity/v1/services;servicesb\x06proto3"

var (
	file_identity_v1_services_skills_service_proto_rawDescOnce sync.Once
	file_identity_v1_services_skills_service_proto_rawDescData []byte
)

func file_identity_v1_services_skills_service_proto_rawDescGZIP() []byte {
	file_identity_v1_services_skills_service_proto_rawDescOnce.Do(func() {
		file_identity_v1_services_skills_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_services_skills_service_proto_rawDesc), len(file_identity_v1_services_skills_service_proto_rawDesc)))
	})
	return file_identity_v1_services_skills_service_proto_rawDescData
}

var file_identity_v1_services_skills_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_identity_v1_services_skills_service_proto_goTypes = []any{
	(*ListSkillCatalogRequest)(nil),  // 0: identity.v1.services.ListSkillCatalogRequest
	(*ListSkillCatalogResponse)(nil), // 1: identity.v1.services.ListSkillCatalogResponse
	(*v1.Query)(nil),                 // 2: common.v1.Query
	(*entities.CatalogSkill)(nil),    // 3: identity.v1.entities.CatalogSkill
	(*v1.PageResponse)(nil),          // 4: common.v1.PageResponse
}
var file_identity_v1_services_skills_service_proto_depIdxs = []int32{
	2, // 0: identity.v1.services.ListSkillCatalogRequest.query:type_name -> common.v1.Query
	3, // 1: identity.v1.services.ListSkillCatalogResponse.skills:type_name -> identity.v1.entities.CatalogSkill
	4, // 2: identity.v1.services.ListSkillCatalogResponse.page:type_name -> common.v1.PageResponse
	0, // 3: identity.v1.services.SkillsService.ListSkillCatalog:input_type -> identity.v1.services.ListSkillCatalogRequest
	1, // 4: identity.v1.services.SkillsService.ListSkillCatalog:output_type -> identity.v1.services.ListSkillCatalogResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_identity_v1_services_skills_service_proto_init() }
func file_identity_v1_services_skills_service_proto_init() {
	if File_identity_v1_services_skills_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_services_skills_service_proto_rawDesc), len(file_identity_v1_services_skills_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_v1_services_skills_service_proto_goTypes,
		DependencyIndexes: file_identity_v1_services_skills_service_proto_depIdxs,
		MessageInfos:      file_identity_v1_services_skills_service_proto_msgTypes,
	}.Build()
	File_identity_v1_services_skills_service_proto = out.File
	file_identity_v1_services_skills_service_proto_goTypes = nil
	file_identity_v1_services_skills_service_proto_depIdxs = nil
}
