// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity/v1/services/users_service.proto

package services

import (
	v1 "github.com/belikoooova/hackaton-platform-api/api/common/v1"
	entities "github.com/belikoooova/hackaton-platform-api/api/identity/v1/entities"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IncludeSkills   bool                   `protobuf:"varint,2,opt,name=include_skills,json=includeSkills,proto3" json:"include_skills,omitempty"`
	IncludeContacts bool                   `protobuf:"varint,3,opt,name=include_contacts,json=includeContacts,proto3" json:"include_contacts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_identity_v1_services_users_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_users_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_users_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserRequest) GetIncludeSkills() bool {
	if x != nil {
		return x.IncludeSkills
	}
	return false
}

func (x *GetUserRequest) GetIncludeContacts() bool {
	if x != nil {
		return x.IncludeContacts
	}
	return false
}

type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	User  *entities.User         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Visibility applied on server:
	// - skills empty if hidden or include_skills=false
	Skills []*entities.Skill `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	// Contacts here are PUBLIC projection only (no per-contact visibility field).
	// - empty if hidden or include_contacts=false
	Contacts      []*entities.Contact `protobuf:"bytes,3,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_identity_v1_services_users_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_users_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_users_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetUser() *entities.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserResponse) GetSkills() []*entities.Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *GetUserResponse) GetContacts() []*entities.Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type BatchGetUsersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserIds         []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	IncludeSkills   bool                   `protobuf:"varint,2,opt,name=include_skills,json=includeSkills,proto3" json:"include_skills,omitempty"`
	IncludeContacts bool                   `protobuf:"varint,3,opt,name=include_contacts,json=includeContacts,proto3" json:"include_contacts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchGetUsersRequest) Reset() {
	*x = BatchGetUsersRequest{}
	mi := &file_identity_v1_services_users_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUsersRequest) ProtoMessage() {}

func (x *BatchGetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_users_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUsersRequest.ProtoReflect.Descriptor instead.
func (*BatchGetUsersRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_users_service_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *BatchGetUsersRequest) GetIncludeSkills() bool {
	if x != nil {
		return x.IncludeSkills
	}
	return false
}

func (x *BatchGetUsersRequest) GetIncludeContacts() bool {
	if x != nil {
		return x.IncludeContacts
	}
	return false
}

type BatchGetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*GetUserResponse     `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUsersResponse) Reset() {
	*x = BatchGetUsersResponse{}
	mi := &file_identity_v1_services_users_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUsersResponse) ProtoMessage() {}

func (x *BatchGetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_users_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUsersResponse.ProtoReflect.Descriptor instead.
func (*BatchGetUsersResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_users_service_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetUsersResponse) GetUsers() []*GetUserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

type ListUsersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           *v1.Query              `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	IncludeSkills   bool                   `protobuf:"varint,2,opt,name=include_skills,json=includeSkills,proto3" json:"include_skills,omitempty"`
	IncludeContacts bool                   `protobuf:"varint,3,opt,name=include_contacts,json=includeContacts,proto3" json:"include_contacts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_identity_v1_services_users_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_users_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_users_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersRequest) GetQuery() *v1.Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ListUsersRequest) GetIncludeSkills() bool {
	if x != nil {
		return x.IncludeSkills
	}
	return false
}

func (x *ListUsersRequest) GetIncludeContacts() bool {
	if x != nil {
		return x.IncludeContacts
	}
	return false
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*GetUserResponse     `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_identity_v1_services_users_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_services_users_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_services_users_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersResponse) GetUsers() []*GetUserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_identity_v1_services_users_service_proto protoreflect.FileDescriptor

const file_identity_v1_services_users_service_proto_rawDesc = "" +
	"\n" +
	"(identity/v1/services/users_service.proto\x12\x14identity.v1.services\x1a\x1cgoogle/api/annotations.proto\x1a\x15common/v1/query.proto\x1a\x1fidentity/v1/entities/user.proto\x1a identity/v1/entities/skill.proto\x1a\"identity/v1/entities/contact.proto\"{\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0einclude_skills\x18\x02 \x01(\bR\rincludeSkills\x12)\n" +
	"\x10include_contacts\x18\x03 \x01(\bR\x0fincludeContacts\"\xb1\x01\n" +
	"\x0fGetUserResponse\x12.\n" +
	"\x04user\x18\x01 \x01(\v2\x1a.identity.v1.entities.UserR\x04user\x123\n" +
	"\x06skills\x18\x02 \x03(\v2\x1b.identity.v1.entities.SkillR\x06skills\x129\n" +
	"\bcontacts\x18\x03 \x03(\v2\x1d.identity.v1.entities.ContactR\bcontacts\"\x83\x01\n" +
	"\x14BatchGetUsersRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12%\n" +
	"\x0einclude_skills\x18\x02 \x01(\bR\rincludeSkills\x12)\n" +
	"\x10include_contacts\x18\x03 \x01(\bR\x0fincludeContacts\"T\n" +
	"\x15BatchGetUsersResponse\x12;\n" +
	"\x05users\x18\x01 \x03(\v2%.identity.v1.services.GetUserResponseR\x05users\"\x8c\x01\n" +
	"\x10ListUsersRequest\x12&\n" +
	"\x05query\x18\x01 \x01(\v2\x10.common.v1.QueryR\x05query\x12%\n" +
	"\x0einclude_skills\x18\x02 \x01(\bR\rincludeSkills\x12)\n" +
	"\x10include_contacts\x18\x03 \x01(\bR\x0fincludeContacts\"}\n" +
	"\x11ListUsersResponse\x12;\n" +
	"\x05users\x18\x01 \x03(\v2%.identity.v1.services.GetUserResponseR\x05users\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.common.v1.PageResponseR\x04page2\x86\x03\n" +
	"\fUsersService\x12s\n" +
	"\aGetUser\x12$.identity.v1.services.GetUserRequest\x1a%.identity.v1.services.GetUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/users/{user_id}\x12\x87\x01\n" +
	"\rBatchGetUsers\x12*.identity.v1.services.BatchGetUsersRequest\x1a+.identity.v1.services.BatchGetUsersResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/users:batchGet\x12w\n" +
	"\tListUsers\x12&.identity.v1.services.ListUsersRequest\x1a'.identity.v1.services.ListUsersResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/users:listBPZNgithub.com/belikoooova/hackaton-platform-api/api/identity/v1/services;servicesb\x06proto3"

var (
	file_identity_v1_services_users_service_proto_rawDescOnce sync.Once
	file_identity_v1_services_users_service_proto_rawDescData []byte
)

func file_identity_v1_services_users_service_proto_rawDescGZIP() []byte {
	file_identity_v1_services_users_service_proto_rawDescOnce.Do(func() {
		file_identity_v1_services_users_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_services_users_service_proto_rawDesc), len(file_identity_v1_services_users_service_proto_rawDesc)))
	})
	return file_identity_v1_services_users_service_proto_rawDescData
}

var file_identity_v1_services_users_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_identity_v1_services_users_service_proto_goTypes = []any{
	(*GetUserRequest)(nil),        // 0: identity.v1.services.GetUserRequest
	(*GetUserResponse)(nil),       // 1: identity.v1.services.GetUserResponse
	(*BatchGetUsersRequest)(nil),  // 2: identity.v1.services.BatchGetUsersRequest
	(*BatchGetUsersResponse)(nil), // 3: identity.v1.services.BatchGetUsersResponse
	(*ListUsersRequest)(nil),      // 4: identity.v1.services.ListUsersRequest
	(*ListUsersResponse)(nil),     // 5: identity.v1.services.ListUsersResponse
	(*entities.User)(nil),         // 6: identity.v1.entities.User
	(*entities.Skill)(nil),        // 7: identity.v1.entities.Skill
	(*entities.Contact)(nil),      // 8: identity.v1.entities.Contact
	(*v1.Query)(nil),              // 9: common.v1.Query
	(*v1.PageResponse)(nil),       // 10: common.v1.PageResponse
}
var file_identity_v1_services_users_service_proto_depIdxs = []int32{
	6,  // 0: identity.v1.services.GetUserResponse.user:type_name -> identity.v1.entities.User
	7,  // 1: identity.v1.services.GetUserResponse.skills:type_name -> identity.v1.entities.Skill
	8,  // 2: identity.v1.services.GetUserResponse.contacts:type_name -> identity.v1.entities.Contact
	1,  // 3: identity.v1.services.BatchGetUsersResponse.users:type_name -> identity.v1.services.GetUserResponse
	9,  // 4: identity.v1.services.ListUsersRequest.query:type_name -> common.v1.Query
	1,  // 5: identity.v1.services.ListUsersResponse.users:type_name -> identity.v1.services.GetUserResponse
	10, // 6: identity.v1.services.ListUsersResponse.page:type_name -> common.v1.PageResponse
	0,  // 7: identity.v1.services.UsersService.GetUser:input_type -> identity.v1.services.GetUserRequest
	2,  // 8: identity.v1.services.UsersService.BatchGetUsers:input_type -> identity.v1.services.BatchGetUsersRequest
	4,  // 9: identity.v1.services.UsersService.ListUsers:input_type -> identity.v1.services.ListUsersRequest
	1,  // 10: identity.v1.services.UsersService.GetUser:output_type -> identity.v1.services.GetUserResponse
	3,  // 11: identity.v1.services.UsersService.BatchGetUsers:output_type -> identity.v1.services.BatchGetUsersResponse
	5,  // 12: identity.v1.services.UsersService.ListUsers:output_type -> identity.v1.services.ListUsersResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_identity_v1_services_users_service_proto_init() }
func file_identity_v1_services_users_service_proto_init() {
	if File_identity_v1_services_users_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_services_users_service_proto_rawDesc), len(file_identity_v1_services_users_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_v1_services_users_service_proto_goTypes,
		DependencyIndexes: file_identity_v1_services_users_service_proto_depIdxs,
		MessageInfos:      file_identity_v1_services_users_service_proto_msgTypes,
	}.Build()
	File_identity_v1_services_users_service_proto = out.File
	file_identity_v1_services_users_service_proto_goTypes = nil
	file_identity_v1_services_users_service_proto_depIdxs = nil
}
