// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
)

type JudgingAssignment struct {
	ID           uuid.UUID `json:"id"`
	HackathonID  uuid.UUID `json:"hackathon_id"`
	SubmissionID uuid.UUID `json:"submission_id"`
	JudgeUserID  uuid.UUID `json:"judge_user_id"`
	AssignedAt   time.Time `json:"assigned_at"`
}

type JudgingEvaluation struct {
	ID           uuid.UUID `json:"id"`
	HackathonID  uuid.UUID `json:"hackathon_id"`
	SubmissionID uuid.UUID `json:"submission_id"`
	JudgeUserID  uuid.UUID `json:"judge_user_id"`
	Score        int32     `json:"score"`
	Comment      string    `json:"comment"`
	EvaluatedAt  time.Time `json:"evaluated_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type JudgingIdempotencyKey struct {
	Key          string    `json:"key"`
	Scope        string    `json:"scope"`
	RequestHash  string    `json:"request_hash"`
	ResponseBlob []byte    `json:"response_blob"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}
