// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ParticipationAndRolesIdempotencyKey struct {
	Key          string    `json:"key"`
	Scope        string    `json:"scope"`
	RequestHash  string    `json:"request_hash"`
	ResponseBlob []byte    `json:"response_blob"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type ParticipationAndRolesParticipation struct {
	HackathonID uuid.UUID   `json:"hackathon_id"`
	UserID      uuid.UUID   `json:"user_id"`
	Status      string      `json:"status"`
	TeamID      pgtype.UUID `json:"team_id"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type ParticipationAndRolesStaffInvitation struct {
	ID              uuid.UUID          `json:"id"`
	HackathonID     uuid.UUID          `json:"hackathon_id"`
	TargetUserID    uuid.UUID          `json:"target_user_id"`
	RequestedRole   string             `json:"requested_role"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	Message         string             `json:"message"`
	Status          string             `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type ParticipationAndRolesStaffRole struct {
	HackathonID uuid.UUID `json:"hackathon_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}
