// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ParticipationAndRolesIdempotencyKey struct {
	Key          string    `json:"key"`
	Scope        string    `json:"scope"`
	RequestHash  string    `json:"request_hash"`
	ResponseBlob []byte    `json:"response_blob"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type ParticipationAndRolesOutboxEvent struct {
	ID            uuid.UUID `json:"id"`
	AggregateID   string    `json:"aggregate_id"`
	AggregateType string    `json:"aggregate_type"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	Status        string    `json:"status"`
	AttemptCount  int32     `json:"attempt_count"`
	LastError     string    `json:"last_error"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type ParticipationAndRolesParticipation struct {
	HackathonID    uuid.UUID   `json:"hackathon_id"`
	UserID         uuid.UUID   `json:"user_id"`
	Status         string      `json:"status"`
	TeamID         pgtype.UUID `json:"team_id"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	MotivationText string      `json:"motivation_text"`
	RegisteredAt   time.Time   `json:"registered_at"`
}

type ParticipationAndRolesParticipationWishedRole struct {
	HackathonID uuid.UUID `json:"hackathon_id"`
	UserID      uuid.UUID `json:"user_id"`
	TeamRoleID  uuid.UUID `json:"team_role_id"`
}

type ParticipationAndRolesStaffInvitation struct {
	ID              uuid.UUID          `json:"id"`
	HackathonID     uuid.UUID          `json:"hackathon_id"`
	TargetUserID    uuid.UUID          `json:"target_user_id"`
	RequestedRole   string             `json:"requested_role"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	Message         string             `json:"message"`
	Status          string             `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type ParticipationAndRolesStaffRole struct {
	HackathonID uuid.UUID `json:"hackathon_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}

type ParticipationAndRolesTeamRoleCatalog struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}
