// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityAvatarUpload struct {
	UploadID    pgtype.UUID        `json:"upload_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Filename    string             `json:"filename"`
	SizeBytes   int64              `json:"size_bytes"`
	ContentType string             `json:"content_type"`
	StorageKey  string             `json:"storage_key"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type IdentityIdempotencyKey struct {
	Key          string    `json:"key"`
	Scope        string    `json:"scope"`
	RequestHash  string    `json:"request_hash"`
	ResponseBlob []byte    `json:"response_blob"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type IdentityOutboxEvent struct {
	ID            pgtype.UUID `json:"id"`
	AggregateID   string      `json:"aggregate_id"`
	AggregateType string      `json:"aggregate_type"`
	EventType     string      `json:"event_type"`
	Payload       []byte      `json:"payload"`
	Status        string      `json:"status"`
	AttemptCount  int32       `json:"attempt_count"`
	LastError     string      `json:"last_error"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type IdentitySkillCatalog struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type IdentityUser struct {
	ID        pgtype.UUID `json:"id"`
	Username  string      `json:"username"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Timezone  string      `json:"timezone"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type IdentityUserCatalogSkill struct {
	UserID         pgtype.UUID `json:"user_id"`
	CatalogSkillID pgtype.UUID `json:"catalog_skill_id"`
}

type IdentityUserContact struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	Type       string      `json:"type"`
	Value      string      `json:"value"`
	Visibility string      `json:"visibility"`
}

type IdentityUserCustomSkill struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

type IdentityUserVisibility struct {
	UserID             pgtype.UUID `json:"user_id"`
	SkillsVisibility   string      `json:"skills_visibility"`
	ContactsVisibility string      `json:"contacts_visibility"`
}
