// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity/v1/common.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VisibilityLevel int32

const (
	VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED VisibilityLevel = 0
	VisibilityLevel_VISIBILITY_LEVEL_PRIVATE     VisibilityLevel = 1
	VisibilityLevel_VISIBILITY_LEVEL_PUBLIC      VisibilityLevel = 2
)

// Enum value maps for VisibilityLevel.
var (
	VisibilityLevel_name = map[int32]string{
		0: "VISIBILITY_LEVEL_UNSPECIFIED",
		1: "VISIBILITY_LEVEL_PRIVATE",
		2: "VISIBILITY_LEVEL_PUBLIC",
	}
	VisibilityLevel_value = map[string]int32{
		"VISIBILITY_LEVEL_UNSPECIFIED": 0,
		"VISIBILITY_LEVEL_PRIVATE":     1,
		"VISIBILITY_LEVEL_PUBLIC":      2,
	}
)

func (x VisibilityLevel) Enum() *VisibilityLevel {
	p := new(VisibilityLevel)
	*p = x
	return p
}

func (x VisibilityLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisibilityLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_v1_common_proto_enumTypes[0].Descriptor()
}

func (VisibilityLevel) Type() protoreflect.EnumType {
	return &file_identity_v1_common_proto_enumTypes[0]
}

func (x VisibilityLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VisibilityLevel.Descriptor instead.
func (VisibilityLevel) EnumDescriptor() ([]byte, []int) {
	return file_identity_v1_common_proto_rawDescGZIP(), []int{0}
}

type ContactType int32

const (
	ContactType_CONTACT_TYPE_UNSPECIFIED ContactType = 0
	ContactType_CONTACT_TYPE_EMAIL       ContactType = 1
	ContactType_CONTACT_TYPE_TELEGRAM    ContactType = 2
	ContactType_CONTACT_TYPE_GITHUB      ContactType = 3
	ContactType_CONTACT_TYPE_LINKEDIN    ContactType = 4
)

// Enum value maps for ContactType.
var (
	ContactType_name = map[int32]string{
		0: "CONTACT_TYPE_UNSPECIFIED",
		1: "CONTACT_TYPE_EMAIL",
		2: "CONTACT_TYPE_TELEGRAM",
		3: "CONTACT_TYPE_GITHUB",
		4: "CONTACT_TYPE_LINKEDIN",
	}
	ContactType_value = map[string]int32{
		"CONTACT_TYPE_UNSPECIFIED": 0,
		"CONTACT_TYPE_EMAIL":       1,
		"CONTACT_TYPE_TELEGRAM":    2,
		"CONTACT_TYPE_GITHUB":      3,
		"CONTACT_TYPE_LINKEDIN":    4,
	}
)

func (x ContactType) Enum() *ContactType {
	p := new(ContactType)
	*p = x
	return p
}

func (x ContactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContactType) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_v1_common_proto_enumTypes[1].Descriptor()
}

func (ContactType) Type() protoreflect.EnumType {
	return &file_identity_v1_common_proto_enumTypes[1]
}

func (x ContactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContactType.Descriptor instead.
func (ContactType) EnumDescriptor() ([]byte, []int) {
	return file_identity_v1_common_proto_rawDescGZIP(), []int{1}
}

var File_identity_v1_common_proto protoreflect.FileDescriptor

const file_identity_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x18identity/v1/common.proto\x12\videntity.v1*n\n" +
	"\x0fVisibilityLevel\x12 \n" +
	"\x1cVISIBILITY_LEVEL_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18VISIBILITY_LEVEL_PRIVATE\x10\x01\x12\x1b\n" +
	"\x17VISIBILITY_LEVEL_PUBLIC\x10\x02*\x92\x01\n" +
	"\vContactType\x12\x1c\n" +
	"\x18CONTACT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONTACT_TYPE_EMAIL\x10\x01\x12\x19\n" +
	"\x15CONTACT_TYPE_TELEGRAM\x10\x02\x12\x17\n" +
	"\x13CONTACT_TYPE_GITHUB\x10\x03\x12\x19\n" +
	"\x15CONTACT_TYPE_LINKEDIN\x10\x04BIZGgithub.com/belikoooova/hackaton-platform-api/api/identity/v1;identityv1b\x06proto3"

var (
	file_identity_v1_common_proto_rawDescOnce sync.Once
	file_identity_v1_common_proto_rawDescData []byte
)

func file_identity_v1_common_proto_rawDescGZIP() []byte {
	file_identity_v1_common_proto_rawDescOnce.Do(func() {
		file_identity_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_common_proto_rawDesc), len(file_identity_v1_common_proto_rawDesc)))
	})
	return file_identity_v1_common_proto_rawDescData
}

var file_identity_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_identity_v1_common_proto_goTypes = []any{
	(VisibilityLevel)(0), // 0: identity.v1.VisibilityLevel
	(ContactType)(0),     // 1: identity.v1.ContactType
}
var file_identity_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_identity_v1_common_proto_init() }
func file_identity_v1_common_proto_init() {
	if File_identity_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_common_proto_rawDesc), len(file_identity_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_v1_common_proto_goTypes,
		DependencyIndexes: file_identity_v1_common_proto_depIdxs,
		EnumInfos:         file_identity_v1_common_proto_enumTypes,
	}.Build()
	File_identity_v1_common_proto = out.File
	file_identity_v1_common_proto_goTypes = nil
	file_identity_v1_common_proto_depIdxs = nil
}
