// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: identity/v1/me_service.proto

package identityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeService_GetMe_FullMethodName            = "/identity.v1.MeService/GetMe"
	MeService_UpdateMe_FullMethodName         = "/identity.v1.MeService/UpdateMe"
	MeService_UpdateMySkills_FullMethodName   = "/identity.v1.MeService/UpdateMySkills"
	MeService_UpdateMyContacts_FullMethodName = "/identity.v1.MeService/UpdateMyContacts"
)

// MeServiceClient is the client API for MeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeServiceClient interface {
	GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error)
	// One endpoint to update "public user fields" for myself.
	UpdateMe(ctx context.Context, in *UpdateMeRequest, opts ...grpc.CallOption) (*UpdateMeResponse, error)
	// Updates my skills AND global skills visibility.
	UpdateMySkills(ctx context.Context, in *UpdateMySkillsRequest, opts ...grpc.CallOption) (*UpdateMySkillsResponse, error)
	// Updates my contacts AND global contacts visibility + per-contact visibility.
	UpdateMyContacts(ctx context.Context, in *UpdateMyContactsRequest, opts ...grpc.CallOption) (*UpdateMyContactsResponse, error)
}

type meServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeServiceClient(cc grpc.ClientConnInterface) MeServiceClient {
	return &meServiceClient{cc}
}

func (c *meServiceClient) GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeResponse)
	err := c.cc.Invoke(ctx, MeService_GetMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meServiceClient) UpdateMe(ctx context.Context, in *UpdateMeRequest, opts ...grpc.CallOption) (*UpdateMeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMeResponse)
	err := c.cc.Invoke(ctx, MeService_UpdateMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meServiceClient) UpdateMySkills(ctx context.Context, in *UpdateMySkillsRequest, opts ...grpc.CallOption) (*UpdateMySkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMySkillsResponse)
	err := c.cc.Invoke(ctx, MeService_UpdateMySkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meServiceClient) UpdateMyContacts(ctx context.Context, in *UpdateMyContactsRequest, opts ...grpc.CallOption) (*UpdateMyContactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMyContactsResponse)
	err := c.cc.Invoke(ctx, MeService_UpdateMyContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeServiceServer is the server API for MeService service.
// All implementations must embed UnimplementedMeServiceServer
// for forward compatibility.
type MeServiceServer interface {
	GetMe(context.Context, *GetMeRequest) (*GetMeResponse, error)
	// One endpoint to update "public user fields" for myself.
	UpdateMe(context.Context, *UpdateMeRequest) (*UpdateMeResponse, error)
	// Updates my skills AND global skills visibility.
	UpdateMySkills(context.Context, *UpdateMySkillsRequest) (*UpdateMySkillsResponse, error)
	// Updates my contacts AND global contacts visibility + per-contact visibility.
	UpdateMyContacts(context.Context, *UpdateMyContactsRequest) (*UpdateMyContactsResponse, error)
	mustEmbedUnimplementedMeServiceServer()
}

// UnimplementedMeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeServiceServer struct{}

func (UnimplementedMeServiceServer) GetMe(context.Context, *GetMeRequest) (*GetMeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMe not implemented")
}
func (UnimplementedMeServiceServer) UpdateMe(context.Context, *UpdateMeRequest) (*UpdateMeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMe not implemented")
}
func (UnimplementedMeServiceServer) UpdateMySkills(context.Context, *UpdateMySkillsRequest) (*UpdateMySkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMySkills not implemented")
}
func (UnimplementedMeServiceServer) UpdateMyContacts(context.Context, *UpdateMyContactsRequest) (*UpdateMyContactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMyContacts not implemented")
}
func (UnimplementedMeServiceServer) mustEmbedUnimplementedMeServiceServer() {}
func (UnimplementedMeServiceServer) testEmbeddedByValue()                   {}

// UnsafeMeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeServiceServer will
// result in compilation errors.
type UnsafeMeServiceServer interface {
	mustEmbedUnimplementedMeServiceServer()
}

func RegisterMeServiceServer(s grpc.ServiceRegistrar, srv MeServiceServer) {
	// If the following call panics, it indicates UnimplementedMeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeService_ServiceDesc, srv)
}

func _MeService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeService_GetMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeServiceServer).GetMe(ctx, req.(*GetMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeService_UpdateMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeServiceServer).UpdateMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeService_UpdateMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeServiceServer).UpdateMe(ctx, req.(*UpdateMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeService_UpdateMySkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMySkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeServiceServer).UpdateMySkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeService_UpdateMySkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeServiceServer).UpdateMySkills(ctx, req.(*UpdateMySkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeService_UpdateMyContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMyContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeServiceServer).UpdateMyContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeService_UpdateMyContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeServiceServer).UpdateMyContacts(ctx, req.(*UpdateMyContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeService_ServiceDesc is the grpc.ServiceDesc for MeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.v1.MeService",
	HandlerType: (*MeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMe",
			Handler:    _MeService_GetMe_Handler,
		},
		{
			MethodName: "UpdateMe",
			Handler:    _MeService_UpdateMe_Handler,
		},
		{
			MethodName: "UpdateMySkills",
			Handler:    _MeService_UpdateMySkills_Handler,
		},
		{
			MethodName: "UpdateMyContacts",
			Handler:    _MeService_UpdateMyContacts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity/v1/me_service.proto",
}
