// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: identity/v1/skills_service.proto

package identityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SkillsService_ListSkillCatalog_FullMethodName = "/identity.v1.SkillsService/ListSkillCatalog"
)

// SkillsServiceClient is the client API for SkillsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkillsServiceClient interface {
	ListSkillCatalog(ctx context.Context, in *ListSkillCatalogRequest, opts ...grpc.CallOption) (*ListSkillCatalogResponse, error)
}

type skillsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkillsServiceClient(cc grpc.ClientConnInterface) SkillsServiceClient {
	return &skillsServiceClient{cc}
}

func (c *skillsServiceClient) ListSkillCatalog(ctx context.Context, in *ListSkillCatalogRequest, opts ...grpc.CallOption) (*ListSkillCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillCatalogResponse)
	err := c.cc.Invoke(ctx, SkillsService_ListSkillCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkillsServiceServer is the server API for SkillsService service.
// All implementations must embed UnimplementedSkillsServiceServer
// for forward compatibility.
type SkillsServiceServer interface {
	ListSkillCatalog(context.Context, *ListSkillCatalogRequest) (*ListSkillCatalogResponse, error)
	mustEmbedUnimplementedSkillsServiceServer()
}

// UnimplementedSkillsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkillsServiceServer struct{}

func (UnimplementedSkillsServiceServer) ListSkillCatalog(context.Context, *ListSkillCatalogRequest) (*ListSkillCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkillCatalog not implemented")
}
func (UnimplementedSkillsServiceServer) mustEmbedUnimplementedSkillsServiceServer() {}
func (UnimplementedSkillsServiceServer) testEmbeddedByValue()                       {}

// UnsafeSkillsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkillsServiceServer will
// result in compilation errors.
type UnsafeSkillsServiceServer interface {
	mustEmbedUnimplementedSkillsServiceServer()
}

func RegisterSkillsServiceServer(s grpc.ServiceRegistrar, srv SkillsServiceServer) {
	// If the following call panics, it indicates UnimplementedSkillsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkillsService_ServiceDesc, srv)
}

func _SkillsService_ListSkillCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillsServiceServer).ListSkillCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillsService_ListSkillCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillsServiceServer).ListSkillCatalog(ctx, req.(*ListSkillCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkillsService_ServiceDesc is the grpc.ServiceDesc for SkillsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkillsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.v1.SkillsService",
	HandlerType: (*SkillsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSkillCatalog",
			Handler:    _SkillsService_ListSkillCatalog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity/v1/skills_service.proto",
}
