// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity/v1/entities/contact.proto

package entities

import (
	v1 "github.com/belikoooova/hackaton-platform-api/api/identity/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          v1.ContactType         `protobuf:"varint,2,opt,name=type,proto3,enum=identity.v1.ContactType" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_identity_v1_entities_contact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_entities_contact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_identity_v1_entities_contact_proto_rawDescGZIP(), []int{0}
}

func (x *Contact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contact) GetType() v1.ContactType {
	if x != nil {
		return x.Type
	}
	return v1.ContactType(0)
}

func (x *Contact) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MyContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       *Contact               `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	Visibility    v1.VisibilityLevel     `protobuf:"varint,2,opt,name=visibility,proto3,enum=identity.v1.VisibilityLevel" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyContact) Reset() {
	*x = MyContact{}
	mi := &file_identity_v1_entities_contact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyContact) ProtoMessage() {}

func (x *MyContact) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_entities_contact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyContact.ProtoReflect.Descriptor instead.
func (*MyContact) Descriptor() ([]byte, []int) {
	return file_identity_v1_entities_contact_proto_rawDescGZIP(), []int{1}
}

func (x *MyContact) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *MyContact) GetVisibility() v1.VisibilityLevel {
	if x != nil {
		return x.Visibility
	}
	return v1.VisibilityLevel(0)
}

var File_identity_v1_entities_contact_proto protoreflect.FileDescriptor

const file_identity_v1_entities_contact_proto_rawDesc = "" +
	"\n" +
	"\"identity/v1/entities/contact.proto\x12\x14identity.v1.entities\x1a\x18identity/v1/common.proto\"]\n" +
	"\aContact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.identity.v1.ContactTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x82\x01\n" +
	"\tMyContact\x127\n" +
	"\acontact\x18\x01 \x01(\v2\x1d.identity.v1.entities.ContactR\acontact\x12<\n" +
	"\n" +
	"visibility\x18\x02 \x01(\x0e2\x1c.identity.v1.VisibilityLevelR\n" +
	"visibilityBPZNgithub.com/belikoooova/hackaton-platform-api/api/identity/v1/entities;entitiesb\x06proto3"

var (
	file_identity_v1_entities_contact_proto_rawDescOnce sync.Once
	file_identity_v1_entities_contact_proto_rawDescData []byte
)

func file_identity_v1_entities_contact_proto_rawDescGZIP() []byte {
	file_identity_v1_entities_contact_proto_rawDescOnce.Do(func() {
		file_identity_v1_entities_contact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_entities_contact_proto_rawDesc), len(file_identity_v1_entities_contact_proto_rawDesc)))
	})
	return file_identity_v1_entities_contact_proto_rawDescData
}

var file_identity_v1_entities_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_identity_v1_entities_contact_proto_goTypes = []any{
	(*Contact)(nil),         // 0: identity.v1.entities.Contact
	(*MyContact)(nil),       // 1: identity.v1.entities.MyContact
	(v1.ContactType)(0),     // 2: identity.v1.ContactType
	(v1.VisibilityLevel)(0), // 3: identity.v1.VisibilityLevel
}
var file_identity_v1_entities_contact_proto_depIdxs = []int32{
	2, // 0: identity.v1.entities.Contact.type:type_name -> identity.v1.ContactType
	0, // 1: identity.v1.entities.MyContact.contact:type_name -> identity.v1.entities.Contact
	3, // 2: identity.v1.entities.MyContact.visibility:type_name -> identity.v1.VisibilityLevel
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_identity_v1_entities_contact_proto_init() }
func file_identity_v1_entities_contact_proto_init() {
	if File_identity_v1_entities_contact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_entities_contact_proto_rawDesc), len(file_identity_v1_entities_contact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_v1_entities_contact_proto_goTypes,
		DependencyIndexes: file_identity_v1_entities_contact_proto_depIdxs,
		MessageInfos:      file_identity_v1_entities_contact_proto_msgTypes,
	}.Build()
	File_identity_v1_entities_contact_proto = out.File
	file_identity_v1_entities_contact_proto_goTypes = nil
	file_identity_v1_entities_contact_proto_depIdxs = nil
}
