// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity/v1/entities/skill.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CatalogSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogSkill) Reset() {
	*x = CatalogSkill{}
	mi := &file_identity_v1_entities_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogSkill) ProtoMessage() {}

func (x *CatalogSkill) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_entities_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogSkill.ProtoReflect.Descriptor instead.
func (*CatalogSkill) Descriptor() ([]byte, []int) {
	return file_identity_v1_entities_skill_proto_rawDescGZIP(), []int{0}
}

func (x *CatalogSkill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CatalogSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CustomSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomSkill) Reset() {
	*x = CustomSkill{}
	mi := &file_identity_v1_entities_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomSkill) ProtoMessage() {}

func (x *CustomSkill) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_entities_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomSkill.ProtoReflect.Descriptor instead.
func (*CustomSkill) Descriptor() ([]byte, []int) {
	return file_identity_v1_entities_skill_proto_rawDescGZIP(), []int{1}
}

func (x *CustomSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Skill struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Skill_Catalog
	//	*Skill_Custom
	Kind          isSkill_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_identity_v1_entities_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_entities_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_identity_v1_entities_skill_proto_rawDescGZIP(), []int{2}
}

func (x *Skill) GetKind() isSkill_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Skill) GetCatalog() *CatalogSkill {
	if x != nil {
		if x, ok := x.Kind.(*Skill_Catalog); ok {
			return x.Catalog
		}
	}
	return nil
}

func (x *Skill) GetCustom() *CustomSkill {
	if x != nil {
		if x, ok := x.Kind.(*Skill_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

type isSkill_Kind interface {
	isSkill_Kind()
}

type Skill_Catalog struct {
	Catalog *CatalogSkill `protobuf:"bytes,1,opt,name=catalog,proto3,oneof"`
}

type Skill_Custom struct {
	Custom *CustomSkill `protobuf:"bytes,2,opt,name=custom,proto3,oneof"`
}

func (*Skill_Catalog) isSkill_Kind() {}

func (*Skill_Custom) isSkill_Kind() {}

var File_identity_v1_entities_skill_proto protoreflect.FileDescriptor

const file_identity_v1_entities_skill_proto_rawDesc = "" +
	"\n" +
	" identity/v1/entities/skill.proto\x12\x14identity.v1.entities\"2\n" +
	"\fCatalogSkill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"!\n" +
	"\vCustomSkill\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x8c\x01\n" +
	"\x05Skill\x12>\n" +
	"\acatalog\x18\x01 \x01(\v2\".identity.v1.entities.CatalogSkillH\x00R\acatalog\x12;\n" +
	"\x06custom\x18\x02 \x01(\v2!.identity.v1.entities.CustomSkillH\x00R\x06customB\x06\n" +
	"\x04kindBPZNgithub.com/belikoooova/hackaton-platform-api/api/identity/v1/entities;entitiesb\x06proto3"

var (
	file_identity_v1_entities_skill_proto_rawDescOnce sync.Once
	file_identity_v1_entities_skill_proto_rawDescData []byte
)

func file_identity_v1_entities_skill_proto_rawDescGZIP() []byte {
	file_identity_v1_entities_skill_proto_rawDescOnce.Do(func() {
		file_identity_v1_entities_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_entities_skill_proto_rawDesc), len(file_identity_v1_entities_skill_proto_rawDesc)))
	})
	return file_identity_v1_entities_skill_proto_rawDescData
}

var file_identity_v1_entities_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_identity_v1_entities_skill_proto_goTypes = []any{
	(*CatalogSkill)(nil), // 0: identity.v1.entities.CatalogSkill
	(*CustomSkill)(nil),  // 1: identity.v1.entities.CustomSkill
	(*Skill)(nil),        // 2: identity.v1.entities.Skill
}
var file_identity_v1_entities_skill_proto_depIdxs = []int32{
	0, // 0: identity.v1.entities.Skill.catalog:type_name -> identity.v1.entities.CatalogSkill
	1, // 1: identity.v1.entities.Skill.custom:type_name -> identity.v1.entities.CustomSkill
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_identity_v1_entities_skill_proto_init() }
func file_identity_v1_entities_skill_proto_init() {
	if File_identity_v1_entities_skill_proto != nil {
		return
	}
	file_identity_v1_entities_skill_proto_msgTypes[2].OneofWrappers = []any{
		(*Skill_Catalog)(nil),
		(*Skill_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_entities_skill_proto_rawDesc), len(file_identity_v1_entities_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_v1_entities_skill_proto_goTypes,
		DependencyIndexes: file_identity_v1_entities_skill_proto_depIdxs,
		MessageInfos:      file_identity_v1_entities_skill_proto_msgTypes,
	}.Build()
	File_identity_v1_entities_skill_proto = out.File
	file_identity_v1_entities_skill_proto_goTypes = nil
	file_identity_v1_entities_skill_proto_depIdxs = nil
}
