// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity/v1/entities/visibility.proto

package entities

import (
	v1 "github.com/belikoooova/hackaton-platform-api/api/identity/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VisibilitySettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        v1.VisibilityLevel     `protobuf:"varint,1,opt,name=skills,proto3,enum=identity.v1.VisibilityLevel" json:"skills,omitempty"`
	Contacts      v1.VisibilityLevel     `protobuf:"varint,2,opt,name=contacts,proto3,enum=identity.v1.VisibilityLevel" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisibilitySettings) Reset() {
	*x = VisibilitySettings{}
	mi := &file_identity_v1_entities_visibility_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisibilitySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilitySettings) ProtoMessage() {}

func (x *VisibilitySettings) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_entities_visibility_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilitySettings.ProtoReflect.Descriptor instead.
func (*VisibilitySettings) Descriptor() ([]byte, []int) {
	return file_identity_v1_entities_visibility_proto_rawDescGZIP(), []int{0}
}

func (x *VisibilitySettings) GetSkills() v1.VisibilityLevel {
	if x != nil {
		return x.Skills
	}
	return v1.VisibilityLevel(0)
}

func (x *VisibilitySettings) GetContacts() v1.VisibilityLevel {
	if x != nil {
		return x.Contacts
	}
	return v1.VisibilityLevel(0)
}

var File_identity_v1_entities_visibility_proto protoreflect.FileDescriptor

const file_identity_v1_entities_visibility_proto_rawDesc = "" +
	"\n" +
	"%identity/v1/entities/visibility.proto\x12\x14identity.v1.entities\x1a\x18identity/v1/common.proto\"\x84\x01\n" +
	"\x12VisibilitySettings\x124\n" +
	"\x06skills\x18\x01 \x01(\x0e2\x1c.identity.v1.VisibilityLevelR\x06skills\x128\n" +
	"\bcontacts\x18\x02 \x01(\x0e2\x1c.identity.v1.VisibilityLevelR\bcontactsBPZNgithub.com/belikoooova/hackaton-platform-api/api/identity/v1/entities;entitiesb\x06proto3"

var (
	file_identity_v1_entities_visibility_proto_rawDescOnce sync.Once
	file_identity_v1_entities_visibility_proto_rawDescData []byte
)

func file_identity_v1_entities_visibility_proto_rawDescGZIP() []byte {
	file_identity_v1_entities_visibility_proto_rawDescOnce.Do(func() {
		file_identity_v1_entities_visibility_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_entities_visibility_proto_rawDesc), len(file_identity_v1_entities_visibility_proto_rawDesc)))
	})
	return file_identity_v1_entities_visibility_proto_rawDescData
}

var file_identity_v1_entities_visibility_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_identity_v1_entities_visibility_proto_goTypes = []any{
	(*VisibilitySettings)(nil), // 0: identity.v1.entities.VisibilitySettings
	(v1.VisibilityLevel)(0),    // 1: identity.v1.VisibilityLevel
}
var file_identity_v1_entities_visibility_proto_depIdxs = []int32{
	1, // 0: identity.v1.entities.VisibilitySettings.skills:type_name -> identity.v1.VisibilityLevel
	1, // 1: identity.v1.entities.VisibilitySettings.contacts:type_name -> identity.v1.VisibilityLevel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_identity_v1_entities_visibility_proto_init() }
func file_identity_v1_entities_visibility_proto_init() {
	if File_identity_v1_entities_visibility_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_entities_visibility_proto_rawDesc), len(file_identity_v1_entities_visibility_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_v1_entities_visibility_proto_goTypes,
		DependencyIndexes: file_identity_v1_entities_visibility_proto_depIdxs,
		MessageInfos:      file_identity_v1_entities_visibility_proto_msgTypes,
	}.Build()
	File_identity_v1_entities_visibility_proto = out.File
	file_identity_v1_entities_visibility_proto_goTypes = nil
	file_identity_v1_entities_visibility_proto_depIdxs = nil
}
