// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package queries

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredentials = `-- name: CreateCredentials :exec
INSERT INTO auth.credentials (user_id, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4)
`

type CreateCredentialsParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	PasswordHash string      `json:"password_hash"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) CreateCredentials(ctx context.Context, arg CreateCredentialsParams) error {
	_, err := q.db.Exec(ctx, createCredentials,
		arg.UserID,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getCredentialsByUserID = `-- name: GetCredentialsByUserID :one
SELECT user_id, password_hash, created_at, updated_at
FROM auth.credentials
WHERE user_id = $1
`

func (q *Queries) GetCredentialsByUserID(ctx context.Context, userID pgtype.UUID) (AuthCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialsByUserID, userID)
	var i AuthCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCredentials = `-- name: UpdateCredentials :exec
UPDATE auth.credentials
SET password_hash = $2, updated_at = $3
WHERE user_id = $1
`

type UpdateCredentialsParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	PasswordHash string      `json:"password_hash"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateCredentials(ctx context.Context, arg UpdateCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateCredentials, arg.UserID, arg.PasswordHash, arg.UpdatedAt)
	return err
}
