// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package queries

import (
	"context"
	"time"
)

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, scope, request_hash, response_blob, created_at, expires_at
FROM auth.idempotency_keys
WHERE key = $1 AND scope = $2 AND expires_at > NOW()
`

type GetIdempotencyKeyParams struct {
	Key   string `json:"key"`
	Scope string `json:"scope"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (AuthIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Key, arg.Scope)
	var i AuthIdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Scope,
		&i.RequestHash,
		&i.ResponseBlob,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const setIdempotencyKey = `-- name: SetIdempotencyKey :execrows
INSERT INTO auth.idempotency_keys (key, scope, request_hash, response_blob, created_at, expires_at)
VALUES ($1, $2, $3, $4, NOW(), $5)
ON CONFLICT (key, scope) DO NOTHING
`

type SetIdempotencyKeyParams struct {
	Key          string    `json:"key"`
	Scope        string    `json:"scope"`
	RequestHash  string    `json:"request_hash"`
	ResponseBlob []byte    `json:"response_blob"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) SetIdempotencyKey(ctx context.Context, arg SetIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setIdempotencyKey,
		arg.Key,
		arg.Scope,
		arg.RequestHash,
		arg.ResponseBlob,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
