// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MatchmakingIdempotencyKey struct {
	Key          string    `json:"key"`
	Scope        string    `json:"scope"`
	RequestHash  string    `json:"request_hash"`
	ResponseBlob []byte    `json:"response_blob"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type MatchmakingOutboxEvent struct {
	ID            uuid.UUID `json:"id"`
	AggregateID   string    `json:"aggregate_id"`
	AggregateType string    `json:"aggregate_type"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	Status        string    `json:"status"`
	AttemptCount  int32     `json:"attempt_count"`
	LastError     string    `json:"last_error"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type MatchmakingParticipation struct {
	HackathonID    uuid.UUID   `json:"hackathon_id"`
	UserID         uuid.UUID   `json:"user_id"`
	Status         string      `json:"status"`
	WishedRoleIds  []uuid.UUID `json:"wished_role_ids"`
	MotivationText pgtype.Text `json:"motivation_text"`
	MotivationTsv  interface{} `json:"motivation_tsv"`
	TeamID         pgtype.UUID `json:"team_id"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type MatchmakingTeam struct {
	TeamID         uuid.UUID   `json:"team_id"`
	HackathonID    uuid.UUID   `json:"hackathon_id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	DescriptionTsv interface{} `json:"description_tsv"`
	IsJoinable     bool        `json:"is_joinable"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type MatchmakingUser struct {
	UserID           uuid.UUID   `json:"user_id"`
	Username         string      `json:"username"`
	AvatarUrl        pgtype.Text `json:"avatar_url"`
	CatalogSkillIds  []uuid.UUID `json:"catalog_skill_ids"`
	CustomSkillNames []string    `json:"custom_skill_names"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type MatchmakingVacancy struct {
	VacancyID       uuid.UUID   `json:"vacancy_id"`
	TeamID          uuid.UUID   `json:"team_id"`
	HackathonID     uuid.UUID   `json:"hackathon_id"`
	Description     pgtype.Text `json:"description"`
	DescriptionTsv  interface{} `json:"description_tsv"`
	DesiredRoleIds  []uuid.UUID `json:"desired_role_ids"`
	DesiredSkillIds []uuid.UUID `json:"desired_skill_ids"`
	SlotsOpen       int32       `json:"slots_open"`
	UpdatedAt       time.Time   `json:"updated_at"`
}
