// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/query.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortDirection int32

const (
	SortDirection_SORT_DIRECTION_UNSPECIFIED SortDirection = 0
	SortDirection_SORT_DIRECTION_ASC         SortDirection = 1
	SortDirection_SORT_DIRECTION_DESC        SortDirection = 2
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "SORT_DIRECTION_UNSPECIFIED",
		1: "SORT_DIRECTION_ASC",
		2: "SORT_DIRECTION_DESC",
	}
	SortDirection_value = map[string]int32{
		"SORT_DIRECTION_UNSPECIFIED": 0,
		"SORT_DIRECTION_ASC":         1,
		"SORT_DIRECTION_DESC":        2,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_query_proto_enumTypes[0].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_common_v1_query_proto_enumTypes[0]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_query_proto_rawDescGZIP(), []int{0}
}

type FilterOperation int32

const (
	FilterOperation_FILTER_OPERATION_UNSPECIFIED FilterOperation = 0
	FilterOperation_FILTER_OPERATION_EQUAL       FilterOperation = 1
	FilterOperation_FILTER_OPERATION_IN          FilterOperation = 2
	FilterOperation_FILTER_OPERATION_CONTAINS    FilterOperation = 3
	FilterOperation_FILTER_OPERATION_PREFIX      FilterOperation = 4
)

// Enum value maps for FilterOperation.
var (
	FilterOperation_name = map[int32]string{
		0: "FILTER_OPERATION_UNSPECIFIED",
		1: "FILTER_OPERATION_EQUAL",
		2: "FILTER_OPERATION_IN",
		3: "FILTER_OPERATION_CONTAINS",
		4: "FILTER_OPERATION_PREFIX",
	}
	FilterOperation_value = map[string]int32{
		"FILTER_OPERATION_UNSPECIFIED": 0,
		"FILTER_OPERATION_EQUAL":       1,
		"FILTER_OPERATION_IN":          2,
		"FILTER_OPERATION_CONTAINS":    3,
		"FILTER_OPERATION_PREFIX":      4,
	}
)

func (x FilterOperation) Enum() *FilterOperation {
	p := new(FilterOperation)
	*p = x
	return p
}

func (x FilterOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_query_proto_enumTypes[1].Descriptor()
}

func (FilterOperation) Type() protoreflect.EnumType {
	return &file_common_v1_query_proto_enumTypes[1]
}

func (x FilterOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOperation.Descriptor instead.
func (FilterOperation) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_query_proto_rawDescGZIP(), []int{1}
}

type Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Direction     SortDirection          `protobuf:"varint,2,opt,name=direction,proto3,enum=common.v1.SortDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_common_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_common_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *Sort) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Sort) GetDirection() SortDirection {
	if x != nil {
		return x.Direction
	}
	return SortDirection_SORT_DIRECTION_UNSPECIFIED
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_common_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_common_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Filter struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Field     string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operation FilterOperation        `protobuf:"varint,2,opt,name=operation,proto3,enum=common.v1.FilterOperation" json:"operation,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Filter_StringValue
	//	*Filter_Int64Value
	//	*Filter_BoolValue
	//	*Filter_StringList
	Value         isFilter_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_common_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_common_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetOperation() FilterOperation {
	if x != nil {
		return x.Operation
	}
	return FilterOperation_FILTER_OPERATION_UNSPECIFIED
}

func (x *Filter) GetValue() isFilter_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Filter) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Filter_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Filter) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*Filter_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *Filter) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Filter_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Filter) GetStringList() *StringList {
	if x != nil {
		if x, ok := x.Value.(*Filter_StringList); ok {
			return x.StringList
		}
	}
	return nil
}

type isFilter_Value interface {
	isFilter_Value()
}

type Filter_StringValue struct {
	StringValue string `protobuf:"bytes,10,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Filter_Int64Value struct {
	Int64Value int64 `protobuf:"varint,11,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Filter_BoolValue struct {
	BoolValue bool `protobuf:"varint,12,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Filter_StringList struct {
	StringList *StringList `protobuf:"bytes,20,opt,name=string_list,json=stringList,proto3,oneof"`
}

func (*Filter_StringValue) isFilter_Value() {}

func (*Filter_Int64Value) isFilter_Value() {}

func (*Filter_BoolValue) isFilter_Value() {}

func (*Filter_StringList) isFilter_Value() {}

type FilterGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterGroup) Reset() {
	*x = FilterGroup{}
	mi := &file_common_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterGroup) ProtoMessage() {}

func (x *FilterGroup) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterGroup.ProtoReflect.Descriptor instead.
func (*FilterGroup) Descriptor() ([]byte, []int) {
	return file_common_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *FilterGroup) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_common_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_common_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *PageRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_common_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_common_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *PageResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Query struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OR between groups, AND inside group.
	FilterGroups  []*FilterGroup `protobuf:"bytes,1,rep,name=filter_groups,json=filterGroups,proto3" json:"filter_groups,omitempty"`
	Sort          []*Sort        `protobuf:"bytes,2,rep,name=sort,proto3" json:"sort,omitempty"`
	Page          *PageRequest   `protobuf:"bytes,10,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_common_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_common_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *Query) GetFilterGroups() []*FilterGroup {
	if x != nil {
		return x.FilterGroups
	}
	return nil
}

func (x *Query) GetSort() []*Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *Query) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_common_v1_query_proto protoreflect.FileDescriptor

const file_common_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x15common/v1/query.proto\x12\tcommon.v1\"T\n" +
	"\x04Sort\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x126\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x18.common.v1.SortDirectionR\tdirection\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x84\x02\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x128\n" +
	"\toperation\x18\x02 \x01(\x0e2\x1a.common.v1.FilterOperationR\toperation\x12#\n" +
	"\fstring_value\x18\n" +
	" \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint64_value\x18\v \x01(\x03H\x00R\n" +
	"int64Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\f \x01(\bH\x00R\tboolValue\x128\n" +
	"\vstring_list\x18\x14 \x01(\v2\x15.common.v1.StringListH\x00R\n" +
	"stringListB\a\n" +
	"\x05value\":\n" +
	"\vFilterGroup\x12+\n" +
	"\afilters\x18\x01 \x03(\v2\x11.common.v1.FilterR\afilters\"I\n" +
	"\vPageRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"6\n" +
	"\fPageResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\"\x95\x01\n" +
	"\x05Query\x12;\n" +
	"\rfilter_groups\x18\x01 \x03(\v2\x16.common.v1.FilterGroupR\ffilterGroups\x12#\n" +
	"\x04sort\x18\x02 \x03(\v2\x0f.common.v1.SortR\x04sort\x12*\n" +
	"\x04page\x18\n" +
	" \x01(\v2\x16.common.v1.PageRequestR\x04page*`\n" +
	"\rSortDirection\x12\x1e\n" +
	"\x1aSORT_DIRECTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SORT_DIRECTION_ASC\x10\x01\x12\x17\n" +
	"\x13SORT_DIRECTION_DESC\x10\x02*\xa4\x01\n" +
	"\x0fFilterOperation\x12 \n" +
	"\x1cFILTER_OPERATION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FILTER_OPERATION_EQUAL\x10\x01\x12\x17\n" +
	"\x13FILTER_OPERATION_IN\x10\x02\x12\x1d\n" +
	"\x19FILTER_OPERATION_CONTAINS\x10\x03\x12\x1b\n" +
	"\x17FILTER_OPERATION_PREFIX\x10\x04BEZCgithub.com/belikoooova/hackaton-platform-api/api/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_query_proto_rawDescOnce sync.Once
	file_common_v1_query_proto_rawDescData []byte
)

func file_common_v1_query_proto_rawDescGZIP() []byte {
	file_common_v1_query_proto_rawDescOnce.Do(func() {
		file_common_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_query_proto_rawDesc), len(file_common_v1_query_proto_rawDesc)))
	})
	return file_common_v1_query_proto_rawDescData
}

var file_common_v1_query_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_v1_query_proto_goTypes = []any{
	(SortDirection)(0),   // 0: common.v1.SortDirection
	(FilterOperation)(0), // 1: common.v1.FilterOperation
	(*Sort)(nil),         // 2: common.v1.Sort
	(*StringList)(nil),   // 3: common.v1.StringList
	(*Filter)(nil),       // 4: common.v1.Filter
	(*FilterGroup)(nil),  // 5: common.v1.FilterGroup
	(*PageRequest)(nil),  // 6: common.v1.PageRequest
	(*PageResponse)(nil), // 7: common.v1.PageResponse
	(*Query)(nil),        // 8: common.v1.Query
}
var file_common_v1_query_proto_depIdxs = []int32{
	0, // 0: common.v1.Sort.direction:type_name -> common.v1.SortDirection
	1, // 1: common.v1.Filter.operation:type_name -> common.v1.FilterOperation
	3, // 2: common.v1.Filter.string_list:type_name -> common.v1.StringList
	4, // 3: common.v1.FilterGroup.filters:type_name -> common.v1.Filter
	5, // 4: common.v1.Query.filter_groups:type_name -> common.v1.FilterGroup
	2, // 5: common.v1.Query.sort:type_name -> common.v1.Sort
	6, // 6: common.v1.Query.page:type_name -> common.v1.PageRequest
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_common_v1_query_proto_init() }
func file_common_v1_query_proto_init() {
	if File_common_v1_query_proto != nil {
		return
	}
	file_common_v1_query_proto_msgTypes[2].OneofWrappers = []any{
		(*Filter_StringValue)(nil),
		(*Filter_Int64Value)(nil),
		(*Filter_BoolValue)(nil),
		(*Filter_StringList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_query_proto_rawDesc), len(file_common_v1_query_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_query_proto_goTypes,
		DependencyIndexes: file_common_v1_query_proto_depIdxs,
		EnumInfos:         file_common_v1_query_proto_enumTypes,
		MessageInfos:      file_common_v1_query_proto_msgTypes,
	}.Build()
	File_common_v1_query_proto = out.File
	file_common_v1_query_proto_goTypes = nil
	file_common_v1_query_proto_depIdxs = nil
}
