// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MentorsIdempotencyKey struct {
	Key          string    `json:"key"`
	Scope        string    `json:"scope"`
	RequestHash  string    `json:"request_hash"`
	ResponseBlob []byte    `json:"response_blob"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type MentorsMessage struct {
	ID              uuid.UUID   `json:"id"`
	TicketID        uuid.UUID   `json:"ticket_id"`
	AuthorUserID    uuid.UUID   `json:"author_user_id"`
	AuthorRole      string      `json:"author_role"`
	Text            string      `json:"text"`
	ClientMessageID pgtype.Text `json:"client_message_id"`
	CreatedAt       time.Time   `json:"created_at"`
}

type MentorsOutboxEvent struct {
	ID            uuid.UUID `json:"id"`
	AggregateID   string    `json:"aggregate_id"`
	AggregateType string    `json:"aggregate_type"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	Status        string    `json:"status"`
	AttemptCount  int32     `json:"attempt_count"`
	LastError     string    `json:"last_error"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type MentorsTicket struct {
	ID                   uuid.UUID          `json:"id"`
	HackathonID          uuid.UUID          `json:"hackathon_id"`
	OwnerKind            string             `json:"owner_kind"`
	OwnerID              uuid.UUID          `json:"owner_id"`
	Status               string             `json:"status"`
	AssignedMentorUserID pgtype.UUID        `json:"assigned_mentor_user_id"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	ClosedAt             pgtype.Timestamptz `json:"closed_at"`
}
