FROM alpine:3.21

WORKDIR /migrations

# Устанавливаем goose
RUN apk add --no-cache curl bash postgresql-client && \
    curl -fsSL https://raw.githubusercontent.com/pressly/goose/master/install.sh | sh

# Копируем все миграции из всех сервисов
COPY internal/auth-service/migrations ./auth
COPY internal/identity-service/migrations ./identity
COPY internal/hackaton-service/migrations ./hackaton
COPY internal/participation-and-roles-service/migrations ./participation
COPY internal/team-service/migrations ./team
COPY internal/mentors-service/migrations ./mentors
COPY internal/matchmaking-service/migrations ./matchmaking
COPY internal/submission-service/migrations ./submission
COPY internal/judging-service/migrations ./judging

# Скрипт для запуска миграций во всех БД
COPY deployments/prod/run-migrations.sh /run-migrations.sh
RUN chmod +x /run-migrations.sh

CMD ["/run-migrations.sh"]
